export const FETCH_PHOTOS_REQUEST = 'FETCH_PHOTOS_REQUEST';
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';
export const FETCH_PHOTOS_FAILURE = 'FETCH_PHOTOS_FAILURE';
export const INCREMENT_PAGE = 'INCREMENT_PAGE';

export const CHANGE_INPUT = 'CHANGE_INPUT';
export const CHANGE_COLLECTIONS = 'CHANGE_COLLECTIONS';
